version: "3"

services:
    db:
        image: mdillon/postgis
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports: 
            - 5432:5432
        restart: always
            
    web:
        build: .
        command: bash -c "python src/occurrence_project/manage.py makemigrations && python src/occurrence_project/manage.py migrate && python src/occurrence_project/manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        