# Generated by Django 2.2.15 on 2020-08-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='por_validar', max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
