# Generated by Django 2.2.15 on 2020-08-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrence_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='status',
            field=models.CharField(default='not_validated', max_length=100),
        ),
    ]
